[project]
name = "opnai-agnts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncio>=3.4.3",
    "chainlit>=2.4.400",
    "openai-agents>=0.0.7",
    "python-dotenv>=1.1.0",
]
